LIBS= -lglfw3 -lGL -lGLU -lGLEW -lX11 -lXxf86vm -lpthread -lXrandr -lXi -lIL #-ltiff -lpng12 -llcms -ljasper -ljpeg -lIlmImf -lz -lImath -lHalf -lIex -lIlmThread 
FLAGS= -std=gnu++11 -O3 -I../include -L../lib

all: Zad4

Zad4:
	g++ ${FLAGS} -o Zad4 *.cpp ${LIBS} 
	
.PHONY: Zad4
